# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8777a5ff63adce61acf3d0f1f5b0b6b7a7f8cd4e4c6138822a4926836b3e2a1d69f45e4c55d19f8910896e7085db34fb218797ae2098e6023c2e3ade9f568e22
  STRIPE_PUBLISHABLE_KEY: pk_test_0toMoQvGpXgflNgR5RwQULxG
  STRIPE_SECRET_KEY: sk_test_tYP3oghQlJ7HNbZy6tcrU5y6

test:
  secret_key_base: 6392cb7f7bc332c1e993b0ca8def8cea211379a3554791f546a4c05502bdb16c146b38b6f6d8c3152d46008198f1b6ffc18a9696c3b93e16a7d2c6d80ea797bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
